### ISSUE TITLE
Annotation completion - eclipse 4.2

### ISSUE THREAD

**Issue by zulus** [pulse00/Symfony-2-Eclipse-Plugin#129]
I'm writing doctrine entity, example:
```php
namespace bkk\Bundle\MBBundle\Entity\Company;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Company structure
 *
 * @author zulus <zulus@w3des.net>
 * @ORM\Entity
 * @ORM\Table(name="company_structure")
 */
class Structure
{
    /**
     * @var int
     * @ORM\Id
     * @ORM\Column(type="bigint")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

   [...]
}
```
Each time when I write @ORM [cmdl+tab] i off course see for ex "@ORM\Column" annotation, but after enter in error logs I see:
`PHPCore plugin internal error`
```
org.eclipse.dltk.core.ModelException: Doctrine\ORM\Mapping\Column [in Doctrine\ORM\Mapping [in Column.php [in doctrine/orm/lib/Doctrine/ORM/Mapping [in vendor [in mb]]]]] does not exist
	at org.eclipse.dltk.internal.core.ModelOperation.runOperation(ModelOperation.java:760)
	at org.eclipse.dltk.internal.core.SourceType.newSupertypeHierarchy(SourceType.java:404)
	at org.eclipse.dltk.internal.core.SourceType.newSupertypeHierarchy(SourceType.java:369)
	at org.eclipse.php.internal.core.typeinference.PHPModelUtils.hasStaticOrConstMember(PHPModelUtils.java:2003)
	at org.eclipse.php.internal.ui.editor.contentassist.PHPCompletionProposalCollector$1.getSuffix(PHPCompletionProposalCollector.java:277)
	at org.eclipse.php.internal.ui.editor.contentassist.PHPCompletionProposalCollector$1.computeReplacementString(PHPCompletionProposalCollector.java:261)
	at org.eclipse.php.internal.ui.editor.contentassist.PHPCompletionProposalCollector$1.getReplacementString(PHPCompletionProposalCollector.java:230)
	at org.eclipse.php.internal.ui.editor.contentassist.PHPCompletionProposal.apply(PHPCompletionProposal.java:82)
	at org.eclipse.dltk.ui.text.completion.AbstractScriptCompletionProposal.apply(AbstractScriptCompletionProposal.java:380)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.insertProposal(CompletionProposalPopup.java:940)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.insertSelectedProposalWithMask(CompletionProposalPopup.java:891)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.verifyKey(CompletionProposalPopup.java:1323)
	at org.eclipse.jface.text.contentassist.ContentAssistant$InternalListener.verifyKey(ContentAssistant.java:808)
	at org.eclipse.jface.text.TextViewer$VerifyKeyListenersManager.verifyKey(TextViewer.java:491)
	at org.eclipse.swt.custom.StyledTextListener.handleEvent(StyledTextListener.java:65)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4134)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1458)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1481)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1466)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1271)
	at org.eclipse.swt.custom.StyledText.handleKeyDown(StyledText.java:5932)
	at org.eclipse.swt.custom.StyledText$7.handleEvent(StyledText.java:5629)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4134)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1458)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1481)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1466)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1495)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1491)
	at org.eclipse.swt.widgets.Canvas.sendKeyEvent(Canvas.java:493)
	at org.eclipse.swt.widgets.Control.doCommandBySelector(Control.java:1060)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5585)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
	at org.eclipse.swt.internal.cocoa.NSResponder.interpretKeyEvents(NSResponder.java:68)
	at org.eclipse.swt.widgets.Composite.keyDown(Composite.java:587)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5495)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Widget.callSuper(Widget.java:221)
	at org.eclipse.swt.widgets.Widget.windowSendEvent(Widget.java:2102)
	at org.eclipse.swt.widgets.Shell.windowSendEvent(Shell.java:2284)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5557)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Display.applicationSendEvent(Display.java:5002)
	at org.eclipse.swt.widgets.Display.applicationProc(Display.java:5151)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
	at org.eclipse.swt.internal.cocoa.NSApplication.sendEvent(NSApplication.java:128)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3616)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1022)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:916)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:86)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:585)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:540)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:124)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:353)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:629)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:584)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1438)
```

Eclipse 4.2, java 1.7 OSX, with latest PDT dev. I have opened two SF project (sf 2.1 and sf 2.0)

**Comment by zulus** [comment]
Fixed in current head.
