### ISSUE TITLE
Routing with empty action or pattern

### ISSUE THREAD

**Issue by zulus** [pulse00/Symfony-2-Eclipse-Plugin#182]
Plugin doesn't support index for:
routing without pattern (exception in logs)
routing without controller (exception in logs)
routing when controller is a service : service_name:action (exception in logs)

**Comment by EquisTango** [comment]
In case it helps, I guess this is a routing without controller:

The following will be send to: ABRT


REPORT

anonymousId         885d4822-0cc8-4eea-8134-d989dbfc8202
name                
email               
comment             
eclipseBuildId      4.6.2.v20170109-1424
eclipseProduct      org.eclipse.platform.ide
javaRuntimeVersion  1.8.0_121-b14
osgiWs              gtk
osgiOs              Linux
osgiOsVersion       4.9.12.fc25
osgiArch            x86_64
severity            UNKNOWN


STATUS

pluginId            com.dubture.symfony.index
pluginVersion       1.3.0.201610140650
code                4
severity            4
message             NULL not allowed for column "CONTROLLER"; SQL statement:
-- IF YOU UPDATE THIS FILE, DON'T FORGET TO INCREMENT THE Schema.VERSION!
-- This is a prepared statement for inserting
-- an element declaration record. Table name
-- is substituted in a runtime.

INSERT INTO ROUTES(
	NAME,
	PATTERN,
	CONTROLLER,
	BUNDLE,
	ACTION,
	PATH)

VALUES(?,?,?,?,?,?);
 [23502-176]
fingerprint         9cbb2b5e8a0cf1711a85a8708a358689

Exception:org.h2.jdbc.JdbcBatchUpdateException: NULL not allowed for column "CONTROLLER"; SQL statement:
-- IF YOU UPDATE THIS FILE, DON'T FORGET TO INCREMENT THE Schema.VERSION!
-- This is a prepared statement for inserting
-- an element declaration record. Table name
-- is substituted in a runtime.

INSERT INTO ROUTES(
	NAME,
	PATTERN,
	CONTROLLER,
	BUNDLE,
	ACTION,
	PATH)

VALUES(?,?,?,?,?,?);
 [23502-176]
	 at org.h2.jdbc.JdbcPreparedStatement.executeBatch(JdbcPreparedStatement.java:1199)
	 at com.dubture.symfony.index.dao.sql.BaseDao.commitInsertions(BaseDao.java:36)
	 at com.dubture.symfony.index.SymfonyIndexer.exitRoutes(SymfonyIndexer.java:130)
	 at com.dubture.symfony.core.builder.AbstractSymfonyVisitor.indexRoutes(AbstractSymfonyVisitor.java:156)
	 at com.dubture.symfony.core.builder.AbstractSymfonyVisitor.loadXML(AbstractSymfonyVisitor.java:205)
	 at com.dubture.symfony.core.builder.AbstractSymfonyVisitor.handleResource(AbstractSymfonyVisitor.java:92)
	 at com.dubture.symfony.core.builder.ResourceVisitor.visit(ResourceVisitor.java:30)
	 at org.eclipse.core.internal.resources.Resource$2.visit(Resource.java:120)
	 at org.eclipse.core.internal.resources.Resource$1.visitElement(Resource.java:84)
	 at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:82)
	 at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
	 at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
	 at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
	 at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
	 at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
	 at org.eclipse.core.internal.watson.ElementTreeIterator.doIteration(ElementTreeIterator.java:87)
	 at org.eclipse.core.internal.watson.ElementTreeIterator.iterate(ElementTreeIterator.java:129)
	 at org.eclipse.core.internal.resources.Resource.accept(Resource.java:94)
	 at org.eclipse.core.internal.resources.Resource.accept(Resource.java:52)
	 at org.eclipse.core.internal.resources.Resource.accept(Resource.java:117)
	 at org.eclipse.core.internal.resources.Resource.accept(Resource.java:105)
	 at com.dubture.symfony.core.builder.SymfonyBuilder.fullBuild(SymfonyBuilder.java:60)
	 at com.dubture.symfony.core.builder.SymfonyBuilder.build(SymfonyBuilder.java:45)
	 at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	 at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	 at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	 at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	 at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	 at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	 at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	 at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	 at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	 at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	 at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	 at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)


BUNDLES

name                com.dubture.symfony.core
version             1.3.0.201610140650

name                com.dubture.symfony.index
version             1.3.0.201610140650

name                org.eclipse.core.jobs
version             3.8.0.v20170109-1424

name                org.eclipse.core.resources
version             3.11.1.v20170109-1424

name                org.eclipse.core.runtime
version             3.12.0.v20170109-1424

name                org.h2
version             1.3.176
