### ISSUE TITLE
luna / dltk doctrine annotation broken

### ISSUE THREAD

**Issue by quazardous** [pulse00/Symfony-2-Eclipse-Plugin#219]
DLTK does not finish due to the doctrine annotation plugin
--------------
java.lang.ClassCastException: org.eclipse.osgi.internal.framework.EquinoxConfiguration$1 cannot be cast to java.lang.String
	at org.eclipse.m2e.logback.configuration.LogHelper.logJavaProperties(LogHelper.java:26)
	at org.eclipse.m2e.logback.configuration.LogPlugin.loadConfiguration(LogPlugin.java:189)
	at org.eclipse.m2e.logback.configuration.LogPlugin.configureLogback(LogPlugin.java:144)
	at org.eclipse.m2e.logback.configuration.LogPlugin.access$2(LogPlugin.java:107)
	at org.eclipse.m2e.logback.configuration.LogPlugin$1.run(LogPlugin.java:62)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Exception in thread "DLTK indexing" java.lang.NoClassDefFoundError: org/antlr/runtime/RecognizerSharedState
	at com.dubture.doctrine.annotation.parser.antlr.AnnotationLexer.<init>(AnnotationLexer.java:53)
	at com.dubture.doctrine.annotation.parser.AnnotationCommentParser.parseChunk(AnnotationCommentParser.java:327)
	at com.dubture.doctrine.annotation.parser.AnnotationCommentParser.parse(AnnotationCommentParser.java:240)
	at com.dubture.doctrine.core.index.DoctrineIndexingVisitorExtension.extractAnnotations(DoctrineIndexingVisitorExtension.java:165)
	at com.dubture.doctrine.core.index.DoctrineIndexingVisitorExtension.processClassDeclaration(DoctrineIndexingVisitorExtension.java:89)
	at com.dubture.doctrine.core.index.DoctrineIndexingVisitorExtension.visit(DoctrineIndexingVisitorExtension.java:79)
	at org.eclipse.php.internal.core.index.PhpIndexingVisitor.visit(PhpIndexingVisitor.java:433)
	at org.eclipse.dltk.ast.declarations.TypeDeclaration.traverse(TypeDeclaration.java:153)
	at org.eclipse.dltk.ast.statements.Block.traverse(Block.java:43)
	at org.eclipse.dltk.ast.declarations.ModuleDeclaration.traverse(ModuleDeclaration.java:71)
	at org.eclipse.php.internal.core.index.PhpIndexingParser.parseSourceModule(PhpIndexingParser.java:30)
	at org.eclipse.dltk.core.index2.AbstractIndexer.indexDocument(AbstractIndexer.java:45)
	at org.eclipse.dltk.internal.core.index.sql.SqlIndexer.indexDocument(SqlIndexer.java:147)
	at org.eclipse.dltk.internal.core.index2.SourceModulesRequest.run(SourceModulesRequest.java:78)
	at org.eclipse.dltk.core.search.indexing.AbstractJob.execute(AbstractJob.java:76)
	at org.eclipse.dltk.internal.core.search.processing.JobManager.run(JobManager.java:467)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.antlr.runtime.RecognizerSharedState cannot be found by com.dubture.doctrine.annotation_1.0.7.201406100859
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:432)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:345)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:337)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)

**Comment by zulus** [comment]
Fixed

**Comment by hongli8881** [comment]
please share how did you fix it. Thank you
