### ISSUE TITLE
"Composer Project from existing package" wizard is very slow

### ISSUE THREAD

**Issue by mniewrzal** [pulse00/Symfony-2-Eclipse-Plugin#221]
Every operation inside wizard is very slow, even name typing. 

Tested with Luna + PDT +  Symfony Feature 1.0.95.201406201738 (Ubuntu 14)

Occasionally it throws such exception (sometimes it crash IDE):

!ENTRY org.eclipse.ui 4 0 2014-10-02 11:39:13.605
!MESSAGE Unhandled event loop exception
!STACK 0
org.eclipse.swt.SWTException: Failed to execute runnable (org.eclipse.swt.SWTError: No more handles)
    at org.eclipse.swt.SWT.error(SWT.java:4441)
    at org.eclipse.swt.SWT.error(SWT.java:4356)
    at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:139)
    at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4147)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3764)
    at org.eclipse.jface.window.Window.runEventLoop(Window.java:832)
    at org.eclipse.jface.window.Window.open(Window.java:808)
    at org.eclipse.ui.internal.actions.NewWizardShortcutAction.run(NewWizardShortcutAction.java:136)
    at org.eclipse.jface.action.Action.runWithEvent(Action.java:519)
    at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:595)
    at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:511)
    at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:420)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4353)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1061)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4172)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3761)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1151)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:636)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:135)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
Caused by: org.eclipse.swt.SWTError: No more handles
    at org.eclipse.swt.SWT.error(SWT.java:4467)
    at org.eclipse.swt.SWT.error(SWT.java:4356)
    at org.eclipse.swt.SWT.error(SWT.java:4327)
    at org.eclipse.swt.internal.ImageList.copyWithAlpha(ImageList.java:179)
    at org.eclipse.swt.internal.ImageList.set(ImageList.java:429)
    at org.eclipse.swt.internal.ImageList.add(ImageList.java:70)
    at org.eclipse.swt.widgets.Button._setImage(Button.java:125)
    at org.eclipse.swt.widgets.Button.setImage(Button.java:942)
    at com.dubture.composer.ui.wizard.project.template.PackagistItem.createStatsPart(PackagistItem.java:137)
    at com.dubture.composer.ui.wizard.project.template.PackagistItem.createContent(PackagistItem.java:93)
    at com.dubture.composer.ui.wizard.project.template.PackagistItem.<init>(PackagistItem.java:59)
    at com.dubture.composer.ui.wizard.project.template.PackageFilterViewer.doCreateViewerItem(PackageFilterViewer.java:98)
    at com.dubture.composer.ui.wizard.project.template.PackageFilterViewer$1.doCreateItem(PackageFilterViewer.java:65)
    at org.eclipse.equinox.internal.p2.ui.discovery.util.ControlListViewer.createNewItem(ControlListViewer.java:244)
    at org.eclipse.equinox.internal.p2.ui.discovery.util.ControlListViewer.refreshAll(ControlListViewer.java:481)
    at org.eclipse.equinox.internal.p2.ui.discovery.util.ControlListViewer.internalRefresh(ControlListViewer.java:365)
    at org.eclipse.jface.viewers.StructuredViewer$7.run(StructuredViewer.java:1500)
    at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1436)
    at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1397)
    at org.eclipse.jface.viewers.StructuredViewer.refresh(StructuredViewer.java:1497)
    at org.eclipse.jface.viewers.StructuredViewer.refresh(StructuredViewer.java:1456)
    at com.dubture.composer.ui.wizard.project.template.PackageFilterViewer$3$1.run(PackageFilterViewer.java:137)
    at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
    at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:136)
    ... 35 more

**Comment by zulus** [comment]
Composer plugin is now part of PDT
