### ISSUE TITLE
Hyperlinks and codeassist are inoperative in Twig editor

### ISSUE THREAD

**Issue by HarryDunne** [pulse00/Symfony-2-Eclipse-Plugin#239]
Hi,

Codeassist and hyperlinks don't work in Twig files for my project. Symfony feature is activated, build paths are correct, other functions of the plugin seem to be working.

I've got this error in Error Log:

```
eclipse.buildId=4.5.1.M20150904-0015
java.version=1.7.0_17
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86, WS=win32, NL=fr_FR
Framework arguments:  -product org.eclipse.epp.package.php.product
Command-line arguments:  -os win32 -ws win32 -arch x86 -product org.eclipse.epp.package.php.product

org.eclipse.dltk.core.index.sql
Error
Wed Dec 02 18:36:52 CET 2015
An exception was thrown while indexing document

java.lang.NullPointerException
    at com.dubture.twig.core.util.TwigModelUtils.isTwigTemplate(TwigModelUtils.java:54)
    at com.dubture.twig.core.parser.TwigSourceParserFactory.parse(TwigSourceParserFactory.java:35)
    at org.eclipse.dltk.core.SourceParserUtil.parse(SourceParserUtil.java:135)
    at org.eclipse.dltk.core.SourceParserUtil.getModuleDeclaration(SourceParserUtil.java:171)
    at org.eclipse.dltk.core.SourceParserUtil.getModuleDeclaration(SourceParserUtil.java:166)
    at org.eclipse.php.internal.core.index.PhpIndexingParser.parseSourceModule(PhpIndexingParser.java:27)
    at com.dubture.symfony.core.index.SymfonyIndexingParser.parseSourceModule(SymfonyIndexingParser.java:37)
    at org.eclipse.dltk.core.index2.AbstractIndexer.indexDocument(AbstractIndexer.java:45)
    at org.eclipse.dltk.internal.core.index.sql.SqlIndexer.indexDocument(SqlIndexer.java:147)
    at org.eclipse.dltk.internal.core.index2.SourceModulesRequest.run(SourceModulesRequest.java:78)
    at org.eclipse.dltk.core.search.indexing.AbstractJob.execute(AbstractJob.java:76)
    at org.eclipse.dltk.internal.core.search.processing.JobManager.run(JobManager.java:469)
    at java.lang.Thread.run(Unknown Source)
```

Regards,

Eric

**Comment by zulus** [comment]
Twig  editor no longer use PHPEditor
