### ISSUE TITLE
version 1.5.0 currently broken with Eclipse PDT 2018.09 ?

### ISSUE THREAD

**Issue by olberger** [pulse00/Symfony-2-Eclipse-Plugin#261]
After installing the Symfony plugin from Eclipse Marketplace on 2018.09, it seems it's no longer possible to create new PHP project from existing code:

The following errors occurs during the indexing:
Errors occurred during the build.
Errors running builder 'Script Builder' on project 'todo'.
org/eclipse/php/internal/core/compiler/ast/visitor/PHPASTVisitor

Hope this helps.

**Comment by zulus** [comment]
Have you full stack from error log? Should work correctly on PDT 6.1 (Eclipse 2018.09).

I personally use http://p2-dev.pdt-extensions.org/ on production.

**Comment by olberger** [comment]
AFAICS, p2-dev now contains v. 1.6.0 which seems to work fine with 2018.09.... Maybe the fact hat it has been released in between (now is "latest", AFAIU), now requires a release of the Symfony plugin too ?

**Comment by zulus** [comment]
LOL, except version bump I do nothing in 1.6. Strange.

I'll check this.

**Comment by olberger** [comment]
Uh... now I'm also puzzled... ;-)

**Comment by FredDut** [comment]
Same problem after upgrading from eclipse-photon or with a fresh install of eclipse-sim-rel.
The project was already existing.
`Errors occurred during the build.
Errors running builder 'Script Builder' on project 'blah'.
org/eclipse/php/internal/core/compiler/ast/visitor/PHPASTVisitor` 

 `An internal error occurred during: "Validating blah".
org/eclipse/php/internal/core/model/PhpModelAccess`

 `Symfony Feature	1.5.0.201806271519	com.dubture.symfony.feature.feature.group	https://github.com/pulse00`
`  Eclipse IDE for PHP Developers	4.8.0.20180619-1200	epp.package.php	Eclipse Packaging Project`
`  PHP Development Tools (PDT)	6.0.0.201806122250	org.eclipse.php.feature.group	Eclipse PDT`

**Comment by FredDut** [comment]
Sorry, the versions with the bug are:
  Eclipse IDE for PHP Developers	4.9.0.20180917-1800	epp.package.php	Eclipse Packaging Project
  PHP Development Tools (PDT)	6.1.0.201808281524	org.eclipse.php.feature.group	Eclipse PDT
  Symfony Feature	1.1.0.201507051747	com.dubture.symfony.feature.feature.group	https://github.com/pulse00

It's very strange: when I install Symfony Feature1.5  from marketplace, after restating eclipse, Symfony Feature is	1.1.0.201507051747	????

**Comment by zulus** [comment]
Could you try http://p2-dev.pdt-extensions.org/ ?

**Comment by FredDut** [comment]
With http://p2-dev.pdt-extensions.org/, I get 1.6 and it's seem OK.
Thanks

**Comment by GMishx** [comment]
I am also facing the same issue. I get following error:
An internal error occurred during: "Initialize DLTK".

Here is the stack trace:
```
java.lang.NoClassDefFoundError: org/eclipse/php/internal/core/compiler/ast/visitor/PHPASTVisitor
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.defineClass(ModuleClassLoader.java:278)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.defineClass(ClasspathManager.java:716)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findClassImpl(ClasspathManager.java:639)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClassImpl(ClasspathManager.java:607)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClassImpl(ClasspathManager.java:587)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:566)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:330)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:396)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:474)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:423)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:415)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at com.dubture.symfony.core.builder.SymfonyBuildParticipantFactory.createBuildParticipant(SymfonyBuildParticipantFactory.java:39)
	at org.eclipse.dltk.internal.core.builder.BuildParticipantManager.createParticipants(BuildParticipantManager.java:203)
	at org.eclipse.dltk.internal.core.builder.BuildParticipantManager.getBuildParticipants(BuildParticipantManager.java:182)
	at org.eclipse.dltk.internal.core.builder.StandardScriptBuilder.initialize(StandardScriptBuilder.java:419)
	at org.eclipse.dltk.internal.core.builder.ScriptBuilder.getScriptBuilders(ScriptBuilder.java:732)
	at org.eclipse.dltk.core.builder.ScriptBuilderUtil$UpgradeCheck.checkProject(ScriptBuilderUtil.java:213)
	at org.eclipse.dltk.core.builder.ScriptBuilderUtil.lambda$0(ScriptBuilderUtil.java:262)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2295)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2317)
	at org.eclipse.dltk.core.builder.ScriptBuilderUtil.rebuildAfterUpgrade(ScriptBuilderUtil.java:268)
	at org.eclipse.dltk.internal.ui.InitializeJob$WorkerJob.run(InitializeJob.java:36)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.ClassNotFoundException: org.eclipse.php.internal.core.compiler.ast.visitor.PHPASTVisitor cannot be found by com.dubture.symfony.core_1.1.0.201507051747
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:512)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:423)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:415)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 27 more
```

I am trying to install from p2-dev again.

**Comment by GMishx** [comment]
The version from p2-dev is working just fine.
