### ISSUE TITLE
Plugin Failing to Instantiate

### ISSUE THREAD

**Issue by dracken** [pulse00/Symfony-2-Eclipse-Plugin#262]
I've been using Eclipse for PHP development for awhile, but needed to learn Symfony, and knew that a helper plugin would benefit development.  Installed the plugin and now my Error Log is spamming with errors like the two messages below and none of the helper objects are working.  I didn't see similar issues opened or closed that relates to this error.

This error is on a my work box which is a Mac with OSX High Sierra with a new install, not upgraded, of Eclipse 2018-19, I have a Windows 10 Pro box at home that I will also try to duplicate when I am home.

I tried restarting the IDE, uninstalling and reinstalling the plugin from here (GitHub) and the Marketplace, also following the install instructions from http://symfony.dubture.com/installation/, but doesn't seem to be any changes.

I haven't disabled other plugins that I've used in the past, but could it be that it's conflicting with other plugins I have already installed?

Thanks!

Using version `1.1.0.201507051747`

### Eclipse
```
Eclipse IDE for PHP Developers

Version: 2018-09 (4.9.0)
Build id: 20180917-1800
```

### Java
```
java 11.0.1 2018-10-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.1+13-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.1+13-LTS, mixed mode)
```

### Message 
```
Error creating instance of org.eclipse.dltk.codeassist.ISelectionEngine
```

### Exception Stack Trace
```
org.eclipse.core.runtime.CoreException: Plug-in "com.dubture.symfony.core" was unable to instantiate class "com.dubture.symfony.core.codeassist.SymfonySelectionEngine".
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.throwException(RegistryStrategyOSGI.java:200)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:194)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:934)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:246)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:63)
	at org.eclipse.dltk.utils.NatureExtensionManager.createInstanceByDescriptor(NatureExtensionManager.java:254)
	at org.eclipse.dltk.utils.NatureExtensionManager.getByNature(NatureExtensionManager.java:213)
	at org.eclipse.dltk.utils.NatureExtensionManager.getInstances(NatureExtensionManager.java:128)
	at org.eclipse.dltk.core.DLTKLanguageManager.getSelectionEngines(DLTKLanguageManager.java:273)
	at org.eclipse.dltk.internal.core.Openable.codeSelect(Openable.java:677)
	at org.eclipse.dltk.internal.core.Openable.codeSelect(Openable.java:698)
	at org.eclipse.dltk.internal.core.AbstractSourceModule.codeSelect(AbstractSourceModule.java:91)
	at org.eclipse.dltk.internal.core.AbstractSourceModule.codeSelect(AbstractSourceModule.java:85)
	at org.eclipse.php.internal.ui.util.PHPSelectionUtil.getSelectionModelElement(PHPSelectionUtil.java:72)
	at org.eclipse.php.internal.ui.actions.OpenTypeHierarchyAction.isEnabled(OpenTypeHierarchyAction.java:161)
	at org.eclipse.php.internal.ui.actions.OpenTypeHierarchyAction.access$0(OpenTypeHierarchyAction.java:155)
	at org.eclipse.php.internal.ui.actions.OpenTypeHierarchyAction$1.run(OpenTypeHierarchyAction.java:117)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.NoClassDefFoundError: org/eclipse/php/internal/core/compiler/ast/visitor/PHPASTVisitor
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.defineClass(ModuleClassLoader.java:279)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.defineClass(ClasspathManager.java:703)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findClassImpl(ClasspathManager.java:626)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClassImpl(ClasspathManager.java:594)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClassImpl(ClasspathManager.java:574)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:553)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:331)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:395)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:473)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:422)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:414)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:153)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3138)
	at java.base/java.lang.Class.getConstructor0(Class.java:3343)
	at java.base/java.lang.Class.newInstance(Class.java:556)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:190)
	... 16 more
Caused by: java.lang.ClassNotFoundException: org.eclipse.php.internal.core.compiler.ast.visitor.PHPASTVisitor cannot be found by com.dubture.symfony.core_1.1.0.201507051747
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:511)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:422)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:414)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:153)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 36 more

```

### Session Data
```
eclipse.buildId=4.9.0.I20180906-0745
java.version=11.0.1
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.php.product -product org.eclipse.epp.package.php.product -product org.eclipse.epp.package.php.product -product org.eclipse.epp.package.php.product -product org.eclipse.epp.package.php.product -product org.eclipse.epp.package.php.product -product org.eclipse.epp.package.php.product -product org.eclipse.epp.package.php.product -product org.eclipse.epp.package.php.product -product org.eclipse.epp.package.php.product -keyring /Users/{user}/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -product org.eclipse.epp.package.php.product -product org.eclipse.epp.package.php.product -product org.eclipse.epp.package.php.product -product org.eclipse.epp.package.php.product -product org.eclipse.epp.package.php.product -product org.eclipse.epp.package.php.product -product org.eclipse.epp.package.php.product -product org.eclipse.epp.package.php.product -product org.eclipse.epp.package.php.product -data file:/Users/{user}/eclipse-workspace/ -product org.eclipse.epp.package.php.product -keyring /Users/{user}/.eclipse_keyring

This is a continuation of log file /Users/{user}/eclipse-workspace/.metadata/.bak_0.log
Created Time: 2018-12-13 09:06:42.666
```

### Message
```
Plug-in "com.dubture.symfony.core" was unable to instantiate class "com.dubture.symfony.core.compiler.SourceElementRequestor".
```

### Exception Stack Trace
```
org.eclipse.core.runtime.CoreException: Plug-in "com.dubture.symfony.core" was unable to instantiate class "com.dubture.symfony.core.compiler.SourceElementRequestor".
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.throwException(RegistryStrategyOSGI.java:200)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:194)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:934)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:246)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:63)
	at org.eclipse.php.internal.core.compiler.PHPSourceElementRequestor.<init>(PHPSourceElementRequestor.java:110)
	at org.eclipse.php.internal.core.compiler.ast.parser.PHPSourceElementParser.createVisitor(PHPSourceElementParser.java:34)
	at org.eclipse.dltk.core.AbstractSourceElementParser.parseSourceModule(AbstractSourceElementParser.java:29)
	at org.eclipse.php.internal.core.compiler.ast.parser.PHPSourceElementParser.parseSourceModule(PHPSourceElementParser.java:29)
	at org.eclipse.dltk.internal.core.AbstractSourceModule.buildStructure(AbstractSourceModule.java:535)
	at org.eclipse.dltk.internal.core.Openable.generateInfos(Openable.java:197)
	at org.eclipse.dltk.internal.core.ModelElement.openWhenClosed(ModelElement.java:199)
	at org.eclipse.dltk.internal.core.SourceModule.makeConsistent(SourceModule.java:263)
	at org.eclipse.dltk.internal.core.ReconcileWorkingCopyOperation.makeConsistent(ReconcileWorkingCopyOperation.java:77)
	at org.eclipse.dltk.internal.core.ReconcileWorkingCopyOperation.executeOperation(ReconcileWorkingCopyOperation.java:57)
	at org.eclipse.dltk.internal.core.ModelOperation.run(ModelOperation.java:703)
	at org.eclipse.dltk.internal.core.ModelOperation.runOperation(ModelOperation.java:769)
	at org.eclipse.dltk.internal.core.SourceModule.reconcile(SourceModule.java:311)
	at org.eclipse.php.internal.ui.editor.validation.PHPReconcilingStrategy.reconcile(PHPReconcilingStrategy.java:135)
	at org.eclipse.php.internal.ui.editor.validation.PHPReconcilingStrategy.access$0(PHPReconcilingStrategy.java:123)
	at org.eclipse.php.internal.ui.editor.validation.PHPReconcilingStrategy$1.run(PHPReconcilingStrategy.java:97)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.php.internal.ui.editor.validation.PHPReconcilingStrategy.reconcile(PHPReconcilingStrategy.java:94)
	at org.eclipse.php.internal.ui.editor.validation.PHPReconcilingStrategy.reconcile(PHPReconcilingStrategy.java:79)
	at org.eclipse.wst.sse.ui.internal.reconcile.DirtyRegionProcessor.process(DirtyRegionProcessor.java:607)
	at org.eclipse.wst.sse.ui.internal.reconcile.DocumentRegionProcessor.process(DocumentRegionProcessor.java:310)
	at org.eclipse.wst.sse.ui.internal.reconcile.StructuredRegionProcessor.process(StructuredRegionProcessor.java:258)
	at org.eclipse.wst.sse.ui.internal.reconcile.DirtyRegionProcessor$BackgroundThread.run(DirtyRegionProcessor.java:692)
Caused by: java.lang.NoClassDefFoundError: org/eclipse/php/internal/core/model/PhpModelAccess
	at com.dubture.symfony.core.compiler.SourceElementRequestor.<init>(SourceElementRequestor.java:47)
	at jdk.internal.reflect.GeneratedConstructorAccessor47.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:190)
	... 26 more
```

### Session Data
```
eclipse.buildId=4.9.0.I20180906-0745
java.version=11.0.1
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.php.product -product org.eclipse.epp.package.php.product -product org.eclipse.epp.package.php.product -product org.eclipse.epp.package.php.product -product org.eclipse.epp.package.php.product -product org.eclipse.epp.package.php.product -product org.eclipse.epp.package.php.product -product org.eclipse.epp.package.php.product -keyring /Users/{user}/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -product org.eclipse.epp.package.php.product -product org.eclipse.epp.package.php.product -product org.eclipse.epp.package.php.product -product org.eclipse.epp.package.php.product -product org.eclipse.epp.package.php.product -product org.eclipse.epp.package.php.product -product org.eclipse.epp.package.php.product -data file:/Users/{user}/eclipse-workspace/ -product org.eclipse.epp.package.php.product -keyring /Users/{user}/.eclipse_keyring
```

**Comment by zulus** [comment]
Try http://p2-dev.pdt-extensions.org

**Comment by zulus** [comment]
Fixed
